### ISSUE TITLE
Verto home page

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/verto#26]
Based on conversations and examples from @Jimb0vlabs, I propose a new version of the home screen:

![image](https://user-images.githubusercontent.com/611529/43918684-b602d19a-9be1-11e8-8c08-76695c275732.png)

This adds transaction history on the bottom, and moves the buttons to the navigation bar.

I'm not tied to having the QR code as large as it is, but I don't see anything else which needs to go there.

Thoughts? @realrhys @papotus @Jimb0vlabs @Mojganahk

**Comment by Mojganahk** [comment]
@shawnlauzon 
-in terms of TRANSACTION HISTORY. it should shown at least 3 last transaction.
-we can put SETTING,SHARING and INFO at the bottom.
-shouldn't  it show SENT or RECEIVED in transaction history?

**Comment by Mojganahk** [comment]
Transaction History items:
-DATE >>>>  August 13, 2018   or  >>>> 2 days ago, 1 hour ago
-STATUS >>>>SENT ,RECEIVED  or  >>>> FROM, TO
-AMOUNT

**Comment by Mojganahk** [comment]
Can it show an equivalent of  BTC or ETH  near the VTX amount?

**Comment by shawnlauzon** [comment]
- If there is only 1 transaction, it couldn't show 3.
- When you say "at the bottom", what do you mean?
- I see nothing wrong with the transaction as is. I think for transactions, having actual dates rather than amount of time from today is less confusing, From To I don't think matters too much, but I don't have a problem if you want to reorganize the transaction contents. And the amount is there in big turquoise letters
- I don't think it's good to continually compare value of VTX to other currencies.

**Comment by Mojganahk** [comment]
1-Lol, I'm saying at least 3, if there is a single one, it's ok.
2- like I specified in the image, it can be a thin and subtle band at the very bottom below the WALLET and BUY VTX. 
![photo_2018-08-09_15-23-47.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e70ef405bdc4707976266456f06624d2a164fd52690e050a1de853524d41aefcd829f2e238248a5c0ce4d66d5f76c03b45a8be854bad1da862da11d1e9e1d30695aa2f2ff58a88453f1b061b81fb5f33a4994ecf5ee406.jpg)

**Comment by Mojganahk** [comment]
@shawnlauzon I can't edit the comment. FYI.

**Comment by shawnlauzon** [comment]
> @shawnlauzon I can't edit the comment. FYI.

You should be able to edit your own comments, but not others. 

If you want to modify the mockups above, I've dropped the source [here](https://github.com/Volentix/verto/tree/master/doc)

**Comment by shawnlauzon** [comment]
> 2- like I specified in the image, it can be a thin and subtle band at the very bottom below the WALLET and BUY VTX.

That would make two rows of tabs, not recommended.

**Comment by shawnlauzon** [comment]
Closing this issue, tracking under Volentix/vlabs#102
