### ISSUE TITLE
User receives a bit of VTX on wallet creation

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/verto#31]
The user should receive some VTX when initially creating a wallet. This somehow needs to be managed so that a user can't create many wallets just to get the VTX.

**Comment by shawnlauzon** [comment]
@papotus Do you have any ideas on how to prevent users from scamming the system and just downloading a bunch of wallets? Remember we want this to be pseudonymous.

**Comment by papotus** [comment]
We make the transaction fee to send higher than the value of the dust, so for instance if the dust they receive is VtX 0.00003141 the minimum balance required to send it out is 0.0001vtx. However to access Volentix apps the requirement is anything >0.00000000 vtx so it would be highly unlikely that someone would want to create all those wallets and emails to correspond. There should also be a requirement of verification to claim the dust one would need to verify a social media account too not just an email. 
1-Limit to first 10000 or 100,000 wallets from unique ip.
2-cannot use same ip for 2 wallets for dust. (Same ip can create unlimited wallets but only claim dust 1 time)
3-cannot use same email again for dust 
4-must verify an approved social media account or perform task like retweet specific traceable sig or similar action TBD.
I’ll think more on this.

**Comment by shawnlauzon** [comment]
We're giving out 100 VTX just for a referral, so doing the work to give out thousandths of a VTX doesn't seem worth it to me.

Perhaps only one dust per IP address makes sense; I'm not sure how easy it is to get lots of IP addresses. I still worry that one person could swoop up a lot of VTX if they know how to do it.

To me, the only option that makes sense would be social media verification, but then it ends up being a similar thing to what we would be offering in Venue. Which may not be a bad thing.

Other thought is not giving out any dust automatically, but have pre-printed cards with the codes that give VTX.

**Comment by papotus** [comment]
https://free.bitcoin.com/

Bitcoin did this for a long time BCH is still doing it. 
I will find a few descent examples to send your way, maybe you have a point. We did however have a reason to want to make sure the balance is >0 VTX and that is what the purpose of this is. 

I will see if I can look into security protocols for dust.


Sent from my iPhone

**Comment by shawnlauzon** [comment]
After downloading the wallet, you need to signin with Google:

![image](https://user-images.githubusercontent.com/611529/44051853-039f5214-9f09-11e8-9892-62c96e147f4d.png)

So if we do that, then that solves the fraud problem (in fact they even say why you need to do that).

**Comment by papotus** [comment]
Right it seems like that is one of the most secure ways. Facebook or Microsoft or others can provide this sort of “layer” maybe we should discuss enabling a Blockchain based one too like civic, or sovereign ID or cryptocoin.pro? Let’s have a call about it 15 minutes to state high level views, pros and cons and brainstorm
