### ISSUE TITLE
User can manually check for wallet updates

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/verto#33]
User should be able to see if we have updated Verto, and then download an update.

I haven't used Electron updating before, but [here is some info](https://electronjs.org/docs/tutorial/updates)

**Comment by Lyncis** [comment]
@shawnlauzon Can I get more info about this one please?

**Comment by shawnlauzon** [comment]
@Lyncis I updated the description

**Comment by shawnlauzon** [comment]
I haven't used this before so don't have a definitive answer. We can use GithHub releases, so perhaps that is enough.

We should support both automatic updates (telling a user that an update is available) and manual updates (allowing the user to check specifically if an update is available). It is ok if we only support one of those right now.

I don't know anything about electron-builder, but it sounds like a good approach.

I'd rather not deploy an update server if we can help it.

Let me know if you'd like to talk more about it.

**Comment by Lyncis** [comment]
I'll add the automated one since it seems to be easier for now.
Then I take a look into a manual one, maybe it is easier than it seems.
Thank you, I'll let you know if I have problems

**Comment by shawnlauzon** [comment]
Please create another issue for automatic updates and this can be returned
to the backlog. Don't hesitate to contact Mojgan if you need anything
designed

**Comment by Lyncis** [comment]
Opened #65 for automatic updates.
Moving this to the backlog for now.
