### ISSUE TITLE
Send graphic assets to development

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/verto#39]
- [ ] PNG images for most images
- [ ] JPG image for background imagess
- [ ] Colour codes

**Comment by Mojganahk** [comment]
@shawnlauzon  I don't have access to the verto board on waffle. FYI

**Comment by Mojganahk** [comment]
Public design Specs contains: 
https://xd.adobe.com/spec/235e0e32-283a-45dd-4557-d76b26d250dd-556f/

====================
LOGO :
![verto - Dark with Accent.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46fe9188378dc3e4cfcdbe51af1de79d3d4e67522a07a62564c7af6aaf50740b0a0c0abe4b4a5a16fba8df2ff5b36e2383080cedd16d5e26c06c16f9be8a0da313f871d51bdaebe5c01982fa3737e683854e3b1d00188cf95f33a49c43cf4abb.png)
![verto - White with Accent.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46fe9188378dc3e4cfdeb74ab058b08320522f330807a02e7e91a164fd52690e050a1de853524d41aefed87da2e53922d9555fead16d5f75943b40abed8417ad1da862da11d1e9e1d30695aa2f2ff58a87453f1b061d89fa5b37a69d4ec15de406.png)

**Comment by Mojganahk** [comment]
background image for the wallet :
![andrew-neel-86570-unsplash.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46e99a9e318794e481ecba4fe905a6c17e166a662717b3277196eb6af3006b1300051bff054a5556f9ab8e7af0b26f75d80f02b9d66d5f74c76f17fdbfd719b713a632c91edbe2e3d7158abd7f37ed998e48341f001b8cff5833a39a4ecd5cf559ac.jpg)

**Comment by shawnlauzon** [comment]
@omarodev See this thread for content

**Comment by Mojganahk** [comment]
onboarding image:
![julius-drost-537534-unsplash.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46e281962a9790e48bfbb050b010a5c77e1374276411ad386089e23bb70037431f1d11f6140b1b56f6eb8c79a1e76a74d95959bed8395874c63d10febed318ea07b232975dc7e7e2de139db17770a599855d3f160f198cfc5835a59f4ec059fe4ae15f18.jpg)

**Comment by Mojganahk** [comment]
@omarodev  please let me know if you needed anything else. thanks.

**Comment by omarodev** [comment]
Please check the attached image by me. 
I need the image for 'verto by volentix'

**Comment by omarodev** [comment]
![screen shot 2018-08-23 at 3 38 42 pm](https://user-images.githubusercontent.com/36173937/44550888-1edb1600-a6eb-11e8-8843-beab66ca513b.png)

**Comment by Mojganahk** [comment]
@omarodev 
logo on first page:
![verto - volentix.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46fe9188378dc3e4cfffb04fa153e49d31046b313916ac217586f76ae5002e03580e18a8125d0d17f5ad8e2ba6b63d228c0d0cb8d7654d68d47f40f2ecdd42e64bef62994597b7b5804dc5eb3824e68e8d483a1706199bb2.png)

**Comment by Mojganahk** [comment]
Fonts:
[fonts.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46ee9b943791c1e5cdf9ad4cae58f3806b1c65262b53a22d2486b62abc1b7f565f5f4ead135e0e43a9ff8139baa47e21d40854b088270a36d43703adbf881eba02bf218a4785b2b88949c2fa70.zip)

**Comment by omarodev** [comment]
@Mojganahk  could you send me PSD or Sketch design file so that I could get Color code and images  easily?

**Comment by Mojganahk** [comment]
@omarodev 
Public design Specs contains:
https://xd.adobe.com/spec/235e0e32-283a-45dd-4557-d76b26d250dd-556f/

Everything is here if you click on each page you will see all the details about fonts, sizes, color codes.

**Comment by omarodev** [comment]
Thank you @Mojganahk  👍 😄  

Could you send me graphics for Wallet Main Page
