### ISSUE TITLE
Verto must show both accounts and wallets for each transaction

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/verto#62]
I just noticed that our UI isn't sufficient. Currently for a transaction we have:

![image](https://user-images.githubusercontent.com/611529/45115375-aaa66680-b11d-11e8-9734-d71208f85312.png)

While the sample IDs here define *who* is sending and receiving funds, it also needs to provide the account. For example, one example is that Alice's trust account receives VTX from the distribution account. There is then two bits of data:

From:
- Account: vtxdistrib
- Wallet: n/a
To:
- Account: vtxtrust
- Wallet: EOS....g3h

The account is always required, while the wallet is required or optional, depending on the type of the account. There is no wallet for the vtxdistrib account because it contains just a big pool of VTX, while the vtxtrust has a line item for each user.

So, @Mojganahk I need the design to support this, and @Lyncis will need to update the UI to conform to the new designs.

**Comment by Lyncis** [comment]
I'll change the page when @Mojganahk updates the UI.

**Comment by Mojganahk** [comment]
@shawnlauzon 
So it misses these two pieces of information, right? 

from:
====
 >   Wallet: n/a

    To:
=====
>    Wallet: EOS....g3h

**Comment by Mojganahk** [comment]
![transaction Record – 2@2x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46fc869b2d9182aa9be0b04de46ff59726542333abe4506b22a5b130fd0e39111d0014f9121c4d4eeefcdb2cf7e038238f0e58e4856a5f74c63c43aae9854ab909a83c990dd4e8e8d51199a26867f5819d4e3614041d8af95e37a8914ace5cf74ff300.png)

**Comment by shawnlauzon** [comment]
This looks good to me, thank you!

**Comment by Lyncis** [comment]
ok, thanks!

**Comment by Mojganahk** [comment]
https://xd.adobe.com/spec/235e0e32-283a-45dd-4557-d76b26d250dd-556f/

**Comment by Lyncis** [comment]
@Mojganahk I used the specs and I have to make font very small to fit a wallet in one line 
![screen shot 2018-09-07 at 3 32 17 pm](https://user-images.githubusercontent.com/8875863/45239464-5af9a380-b2b3-11e8-9252-b98ede86c477.png)

**Comment by shawnlauzon** [comment]
That looks unreadable. It's better to have the wallet address truncated (e.g. EOS5vB...MtHTbW)

**Comment by Lyncis** [comment]
ok, I'll change this
