### ISSUE TITLE
User can create EOS account

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/verto#8]
An EOS account costs money, so this is something that cannot be done automatically.

**Comment by sylvaincormier** [comment]
The required data will be the JSON-Body of the HTTP request and will look something like this.

{ 
 expiration: 1,
 ref_block_num: 1,
 ref_block_prefix: 1,
 max_net_usage_words: 1,
 max_cpu_usage_ms: 1,
 delay_sec: 1,
 context_free_actions: [ '' ],
 actions: [ "create account" ],
 signatures: [ keys ],
 context_free_data: [ '' ],
 transaction_extensions: '' },
}
